- name: Generate server certificates from inventory
  include_tasks:
    file: server_single.yml
    apply:
      delegate_to: localhost
      run_once: false
  loop: "{{ groups['etcd'] }}"
  loop_control:
    loop_var: etcd_host

