- name: Read CA cert
  slurp:
    src: "{{ k8s_cert_dir }}/k8s_ca.crt"
  register: k8s_ca_cert

- name: Read kube-scheduler cert
  slurp:
    src: "{{ k8s_cert_dir }}/kube_scheduler.crt"
  register: k8s_sc_cert

- name: Read kube-scheduler key
  slurp:
    src: "{{ k8s_cert_dir }}/kube_scheduler.key"
  register: k8s_sc_key

# -------------------------
# 生成 kubeconfig
# -------------------------
- name: Generate kube-scheduler kubeconfig
  copy:
    dest: "{{ k8s_base_dir }}/kube-scheduler.kubeconfig"
    mode: '0644'
    content: |
      apiVersion: v1
      kind: Config

      clusters:
      - name: "{{ cluster_name | string }}"
        cluster:
          server: {{ k8s_api_server }}
          certificate-authority-data: {{ k8s_ca_cert.content }}

      users:
      - name: system:kube-scheduler
        user:
          client-certificate-data: {{ k8s_sc_cert.content }}
          client-key-data: {{ k8s_sc_key.content }}

      contexts:
      - name: system:kube-scheduler
        context:
          cluster: "{{ cluster_name | string }}"
          user: system:kube-scheduler

      current-context: system:kube-scheduler
