[control]
localhost ansible_connection=local

[kube_control_plane]
node-1 ansible_host=10.10.120.142 #ansible_user=work

[kube_node]
node-2 ansible_host=10.10.120.143 #ansible_user=work
node-3 ansible_host=10.10.120.144 #ansible_user=work

[etcd]
node-1 ansible_host=10.10.120.142
node-2 ansible_host=10.10.120.143
node-3 ansible_host=10.10.120.144

[k8s_cluster:children]
kube_control_plane
kube_node

[all:vars]
ansible_user=ansible
ansible_become=true
ansible_become_method=sudo
ansible_ssh_private_key_file=~/.ssh/ansible_id_rsa
