package heartbeat

// handle_k8s.go — implements the "install_k8s" command.
//
// Flow:
//  1. Parse payload {script, cluster_id, cluster_name}.
//  2. Write the shell script to a temp file.
//  3. Execute via bash -e, with real-time stdout/stderr streaming:
//       • Each line is posted to the server via POST /api/v1/task/log
//         so the frontend progress page shows live output.
//       • A local buffer accumulates the last N lines for CommandResult.Output.
//  4. Report the final CommandResult (success / failed) back to the server.
//
// The script itself is generated by the backend (ft-backend/handlers/k8s_ansible.go)
// and drives Ansible playbooks. The client only executes it; it does not interpret
// the deployment logic.

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"ft-client/internal/logger"
	"ft-client/internal/model"
)

// k8sDeployPayload is the JSON structure the server puts in Command.Payload
// for an "install_k8s" command.
type k8sDeployPayload struct {
	Script      string `json:"script"`
	ClusterID   string `json:"cluster_id"`
	ClusterName string `json:"cluster_name"`
}

// handleInstallK8s executes a Kubernetes deployment and streams logs back.
func (s *Service) handleInstallK8s(ctx context.Context, cmd model.Command) *model.CommandResult {
	result := &model.CommandResult{
		TaskID:    cmd.TaskID,
		SubTaskID: cmd.SubTaskID,
		ClientID:  s.cfg.Client.ID,
	}

	logger.Info("install_k8s: starting deployment",
		"task_id", cmd.TaskID,
		"sub_task_id", cmd.SubTaskID,
	)

	// --- 1. Parse payload ---
	var payload k8sDeployPayload
	if err := json.Unmarshal(cmd.Payload, &payload); err != nil {
		return k8sFailResult(result, "payload parse error: "+err.Error())
	}
	if payload.Script == "" {
		return k8sFailResult(result, "deploy script is empty in payload")
	}

	logger.Info("install_k8s: cluster info",
		"cluster_id", payload.ClusterID,
		"cluster_name", payload.ClusterName,
	)

	// --- 2. Write script to a temp file ---
	scriptPath := filepath.Join(os.TempDir(), fmt.Sprintf("ofp-k8s-%s.sh", payload.ClusterID))
	if err := os.WriteFile(scriptPath, []byte(payload.Script), 0700); err != nil {
		return k8sFailResult(result, "failed to write deploy script: "+err.Error())
	}
	defer os.Remove(scriptPath)

	logger.Info("install_k8s: script written", "path", scriptPath)

	// --- 3. Build execution context ---
	// Use command timeout when provided, otherwise default to 60 minutes.
	timeout := time.Duration(cmd.Timeout) * time.Second
	if timeout <= 0 {
		timeout = 60 * time.Minute
	}
	execCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	postLog := func(level, msg string) {
		entry := &model.LogEntry{
			TaskID:    cmd.TaskID,
			SubTaskID: cmd.SubTaskID,
			ClientID:  s.cfg.Client.ID,
			Level:     level,
			Message:   msg,
		}
		// PostLog is best-effort; log locally if it fails.
		if err := s.client.PostLog(context.Background(), entry); err != nil {
			logger.Warn("install_k8s: failed to post log line to server",
				"error", err,
				"message", msg,
			)
		}
	}

	postLog("info", fmt.Sprintf("=== OpsFleetPilot K8s Deployment: %s ===", payload.ClusterName))
	postLog("info", fmt.Sprintf("Script path: %s", scriptPath))

	// --- 4. Execute the script ---
	bashCmd := exec.CommandContext(execCtx, "bash", "-e", scriptPath)
	bashCmd.Env = append(os.Environ(), "ANSIBLE_FORCE_COLOR=false", "ANSIBLE_STDOUT_CALLBACK=default")

	stdoutPipe, err := bashCmd.StdoutPipe()
	if err != nil {
		return k8sFailResult(result, "stdout pipe: "+err.Error())
	}
	stderrPipe, err := bashCmd.StderrPipe()
	if err != nil {
		return k8sFailResult(result, "stderr pipe: "+err.Error())
	}

	if err := bashCmd.Start(); err != nil {
		return k8sFailResult(result, "start script: "+err.Error())
	}

	logger.Info("install_k8s: script started", "pid", bashCmd.Process.Pid)
	postLog("info", fmt.Sprintf("Deploy process started (PID %d)", bashCmd.Process.Pid))

	// --- 5. Stream stdout and stderr concurrently ---
	// We accumulate up to lastLinesBuf lines for CommandResult.Output.
	const maxOutputLines = 200
	outputLines := make([]string, 0, maxOutputLines)
	var outputMu = make(chan struct{}, 1) // single-element channel as mutex

	streamPipe := func(pipe io.Reader, level string) {
		scanner := bufio.NewScanner(pipe)
		scanner.Buffer(make([]byte, 1024*1024), 1024*1024) // 1MB buffer per line
		for scanner.Scan() {
			line := scanner.Text()
			if line == "" {
				continue
			}

			// Determine log level from line content.
			logLevel := level
			lower := strings.ToLower(line)
			if strings.Contains(lower, "error") || strings.Contains(lower, "failed") || strings.Contains(lower, "fatal") {
				logLevel = "error"
			} else if strings.Contains(lower, "warn") || strings.Contains(lower, "warning") {
				logLevel = "warn"
			}

			postLog(logLevel, line)
			// Mirror script output to local log at matching level so
			// operators can debug without needing server-side task logs.
			if logLevel == "error" {
				logger.Error("install_k8s script", "line", line)
			} else {
				logger.Debug("install_k8s output", "line", line)
			}

			// Append to output buffer (keep last maxOutputLines).
			select {
			case outputMu <- struct{}{}:
				outputLines = append(outputLines, line)
				if len(outputLines) > maxOutputLines {
					outputLines = outputLines[len(outputLines)-maxOutputLines:]
				}
				<-outputMu
			default:
			}
		}
	}

	done := make(chan struct{}, 2)
	go func() { streamPipe(stdoutPipe, "info"); done <- struct{}{} }()
	go func() { streamPipe(stderrPipe, "error"); done <- struct{}{} }()

	// Wait for both streams to finish.
	<-done
	<-done

	// --- 6. Wait for the process to exit ---
	waitErr := bashCmd.Wait()

	var outputMuBuf bytes.Buffer
	select {
	case outputMu <- struct{}{}:
		outputMuBuf.WriteString(strings.Join(outputLines, "\n"))
		<-outputMu
	default:
	}
	result.Output = outputMuBuf.String()

	if waitErr != nil {
		if execCtx.Err() == context.DeadlineExceeded {
			msg := fmt.Sprintf("deployment timed out after %s", timeout)
			logger.Error("install_k8s: "+msg, "cluster", payload.ClusterName)
			postLog("error", "=== TIMEOUT: "+msg+" ===")
			return k8sFailResult(result, msg)
		}

		exitCode := 1
		if exitErr, ok := waitErr.(*exec.ExitError); ok {
			exitCode = exitErr.ExitCode()
		}
		msg := fmt.Sprintf("script exited with code %d: %v", exitCode, waitErr)
		logger.Error("install_k8s: "+msg, "cluster", payload.ClusterName)
		postLog("error", "=== FAILED: "+msg+" ===")
		result.ExitCode = exitCode
		result.Status = model.StatusFailed
		result.Error = msg
		return result
	}

	// --- 7. Success ---
	successMsg := fmt.Sprintf("=== K8s cluster '%s' deployed successfully ===", payload.ClusterName)
	logger.Info("install_k8s: " + successMsg)
	postLog("info", successMsg)

	result.Status = model.StatusSuccess
	result.ExitCode = 0
	return result
}

// k8sFailResult populates a failed CommandResult with the given error message.
func k8sFailResult(r *model.CommandResult, errMsg string) *model.CommandResult {
	logger.Error("install_k8s failed", "error", errMsg)
	r.Status = model.StatusFailed
	r.ExitCode = 1
	r.Error = errMsg
	return r
}
