---
- name: Create kube-proxy client private key
  community.crypto.openssl_privatekey:
    path: "{{ k8s_cert_dir }}/kube-proxy.key"
    size: 2048
    type: RSA
    mode: "0600"
  delegate_to: localhost
  run_once: true

- name: Create kube-proxy client CSR
  community.crypto.openssl_csr:
    path: "{{ k8s_cert_dir }}/kube-proxy.csr"
    privatekey_path: "{{ k8s_cert_dir }}/kube-proxy.key"
    common_name: system:kube-proxy
    extended_key_usage:
      - clientAuth
    state: present
  delegate_to: localhost
  run_once: true

- name: Sign kube-proxy client certificate
  community.crypto.x509_certificate:
    path: "{{ k8s_cert_dir }}/kube-proxy.crt"
    csr_path: "{{ k8s_cert_dir }}/kube-proxy.csr"
    provider: ownca
    ownca_path: "{{ k8s_cert_dir }}/k8s_ca.crt"
    ownca_privatekey_path: "{{ k8s_cert_dir }}/k8s_ca.key"
    ownca_not_after: +3650d
  delegate_to: localhost
  run_once: true
