- name: Read CA cert
  slurp:
    src: "{{ k8s_cert_dir }}/k8s_ca.crt"
  register: k8s_ca_cert

- name: Read controller-manager cert
  slurp:
    src: "{{ k8s_cert_dir }}/kube_controller_manager.crt"
  register: k8s_cm_cert

- name: Read controller-manager key
  slurp:
    src: "{{ k8s_cert_dir }}/kube_controller_manager.key"
  register: k8s_cm_key

# -------------------------
# 生成 kubeconfig
# -------------------------
- name: Generate controller-manager kubeconfig
  copy:
    dest: "{{ k8s_base_dir }}/controller-manager.kubeconfig"
    mode: '0644'
    content: |
      apiVersion: v1
      kind: Config

      clusters:
      - name: {{ cluster_name }}
        cluster:
          server: {{ k8s_api_server }}
          certificate-authority-data: {{ k8s_ca_cert.content }}

      users:
      - name: system:kube-controller-manager
        user:
          client-certificate-data: {{ k8s_cm_cert.content }}
          client-key-data: {{ k8s_cm_key.content }}

      contexts:
      - name: system:kube-controller-manager
        context:
          cluster: {{ cluster_name }}
          user: system:kube-controller-manager

      current-context: system:kube-controller-manager
